version: "3.7"
services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker_network
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - docker_network
    restart: always
  
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    restart: always

networks:
  docker_network:

volumes: 
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: "${WORDPRESS_VOLUME_PATH}"
      o: bind
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: "${DB_VOLUME_PATH}"
      o: bind
